### ISSUE TITLE
issue with loading items-attribute data

### ISSUE THREAD

**Issue by astrodi** [zenogantner/MyMediaLite#452]
Hello, I try to use MML with item-recommendation in my diploma thesis. Everything works fine before I add --attribute-file flag.

![01](https://cloud.githubusercontent.com/assets/10756333/11561826/37915d2a-99ca-11e5-9bd2-c56c3c794b4f.png)
I tried to remove first line of attribute file, but still same:
![02](https://cloud.githubusercontent.com/assets/10756333/11561827/37944bde-99ca-11e5-8565-9f3860ded7bb.png)

Here is my attribute dataset example: 
![03](https://cloud.githubusercontent.com/assets/10756333/11561828/3794efee-99ca-11e5-8529-ebf6ded8e7c7.png)

Can you help me with identifying, where the problem is? (some kind of formatting?)

thank you for any advice!

Dominik Imrich, UPJS Slovakia

**Comment by zenogantner** [comment]
Hi, MML only supports binary attributes. See the documentation on this page:
http://mymedialite.net/documentation/attribute_files.html

**Comment by astrodi** [comment]
Thank you, I very appreciate your interest and answer.
I feel sorry, my fault, I didn't notice this before. 
I'll try convert my data into required format.
So thank you again, have a nice week

**Comment by zenogantner** [comment]
No worries, Dominik. Let me know if you have other questions.
