### ISSUE TITLE
Are there any models here that actually implement efficient incremental updates?

### ISSUE THREAD

**Issue by doctorpangloss** [zenogantner/MyMediaLite#478]
Your docs mention incremental rating prediction as a more efficient way to add data to an existing model:

> By incremental training we mean that after each update, the recommender does not perform a complete re-training using all data, but only a brief update procedure taking into account the update and only a subset of the existing training data. This interface does not prevent you from doing a complete re-training when implementing a new class. This makes sense e.g. for simple average-based models.

The question is: **do any models actually do a brief update procedure, or do they all do a complete re-training in practice?**

Here's my take, looking at implementations only and assuming one additional rating is added to the given model:

 - `WRMF`: **Yes**, `Optimize` is only called twice, once on the user and once on the item, and only a single row from the data matrix is fetched in the `Optimize` call. Also, `RetrainItem` and `RetrainUser` are definitely actually called by `AddFeedback`.
 - `MostPopular`: **Yes**, but that's not saying much.
 - `BPRMF`: **Hard to Say**, there's something very fishy going on with the `num_item_iterations` calculation in `RetrainItem` that obscures, to me, whether it's actually doing an update, but it appears an effort to make it more efficient was made.
 - `KNN` and its inheritors: **Hard to Say**. `FoldIn` appears to be more efficient, but the `RetrainUser`/`RetrainItem` implementations seem to do a full retraining because every item/user is revisited and the same calls as done in regular training are made.
 - `SLIM` and its inheritors: **No**, because `AddFeedback` isn't overridden and `RetrainItem` is never called.
 - `MatrixFactorization` and its inheritors: **No**, because `AddRatings` base implementation retrains every user and item and no class overrides this method.

**Comment by zenogantner** [comment]
Hello, BPRMF does perform a brief update, however I would perform additional measurements to see whether everything is tuned correctly before deploying it for anything practical ...

Hint: Feel free to discuss further questions here: mymedialite@googlegroups.com

**Comment by doctorpangloss** [comment]
Thanks, I think maybe consider throwing `NotImplementedException` for the ones that definitely do not do incremental updates? Or document otherwise?
