### ISSUE TITLE
Executing MyMediaLite Reg

### ISSUE THREAD

**Issue by Sangeethapsgtech** [zenogantner/MyMediaLite#481]
Hello 
         Iam newbie to recommender. I tried using mymedialite in google colab. I used mymedialite binary package and i get the following errors. Iam not sure how to install mymedialite in colab before using it. Kindly suggest solution This is the command iam trying to execute
![image](https://user-images.githubusercontent.com/49776911/77215652-53b78500-6b3b-11ea-975d-b8db0d5f4622.png)
This is the error i get
![image](https://user-images.githubusercontent.com/49776911/77215620-1521ca80-6b3b-11ea-9c80-eb221d58e6e7.png)
Regards
S.Sangeetha

**Comment by zenogantner** [comment]
If you install the binary package, there is no need to build anything via
"make".

Please try to isolate the problem further, on the screenshot you have error
messages left and right, even before running "make".

What are you trying to achieve?
Which exact step do you execute?
Which exact results do you expect?
What happens instead?

I hope this helps.

Sangeethapsgtech <notifications@github.com> schrieb am Sa., 21. März 2020,
01:44:

**Comment by Sangeethapsgtech** [comment]
Hello,
Thank you for the reply i used the binary file in ubuntu machine and got
the results. But is there any possibility of executing the medialite
recommendation library in google colab?

**Comment by zenogantner** [comment]
No experience with Google Colab.

Happy to hear if anyone finds out something...

Sangeethapsgtech <notifications@github.com> schrieb am Mo., 23. März 2020,
09:11:
